language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

cache:
  directories:
    - bin

env:
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*@dev
  - SYMFONY_VERSION=dev-master

sudo: false

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=dev-master
    - env: SYMFONY_VERSION=2.8.*@dev
    - php: hhvm
  exclude:
    - env: SYMFONY_VERSION=dev-master
      php: 5.4

install:
  - "[ ! -f bin/selenium.jar ] && wget -O bin/selenium.jar http://selenium-release.storage.googleapis.com/2.48/selenium-server-standalone-2.48.2.jar || true"
  - composer require symfony/security-bundle:${SYMFONY_VERSION} -n --prefer-source
  - php features/fixtures/project/app/console assets:install --symlink features/fixtures/project/web

before_script:
  - nohup php -S localhost:8080 -t features/fixtures/project/web > /tmp/server.log 2>&1 &
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - java -jar bin/selenium.jar > /dev/null &
  - sleep 5

script:
  - bin/phpspec run -f pretty
  - bin/behat --no-snippets --format=progress --profile=travis -v

after_failure:
  - cat /tmp/FSiAdminSecurityBundle/logs/test.log
  - cat /tmp/server.log
