language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

dist: focal

sudo: required

addons:
    firefox: "47.0.1"

services: xvfb

matrix:
  include:
    - php: 7.4
      env:
        - COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.4
    - php: 8.0
    - php: 8.1

before_install:
  - phpenv config-rm xdebug.ini
  - composer update $COMPOSER_FLAGS
  - wget --no-clobber -O vendor/bin/selenium.jar http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar || true

before_script:
  - nohup php -S localhost:8080 -t features/fixtures/project/public > /tmp/server.log 2>&1 &
  - java -jar vendor/bin/selenium.jar > /dev/null 2>&1 &
  - sleep 5
  - features/fixtures/project/bin/console assets:install --symlink features/fixtures/project/public

script:
  - vendor/bin/phpcs
  - vendor/bin/phpspec run -f pretty
  - vendor/bin/phpstan analyze -c phpstan.neon
  - vendor/bin/behat --no-snippets --profile=travis

after_failure:
  - cat /tmp/FSiAdminSecurityBundle/logs/test.log
  - cat /tmp/server.log
