fsi_admin_activation:
    path: /activation/activate/{token}
    controller: admin_security.controller.activation:activateAction

fsi_admin_activation_change_password:
    path: /activation/change-password/{token}
    controller: admin_security.controller.activation:changePasswordAction
