fsi_admin_security_password_reset_request:
    path: /password-reset/request
    controller: admin_security.controller.password_reset.request

fsi_admin_security_password_reset_change_password:
    path: /password-reset/change-password/{token}
    controller: admin_security.controller.password_reset.change_password
