fsi_admin_security_user_login:
    path: /login
    controller: admin_security.controller.login

fsi_admin_security_user_check:
    path: /login_check

fsi_admin_security_user_logout:
    path: /logout

fsi_admin_change_password:
    path: /change-password
    controller: admin_security.controller.change_password
